name: Deploy to PROD

on:
  push:
    branches:
      - main
workflow_dispatch: # Allows you to trigger the job manually from GitHub UI

jobs:
  refresh-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Coalesce CLI
        run: npm install -g @coalescesoftware/coa
      
      - name: Create Deployment Plan
        run: npx coa plan --config COA_CONFIG --out ./coa-plan2 --debug

       - name: Print version
        run: npx coa --version
        
      - name: Trigger Coalesce Job
        env:
          # Assumes you have COA_CONFIG stored in GitHub Secrets
          COA_CONFIG: ${{ secrets.COA_CONFIG }}
        # "coa refresh" triggers a pipeline run in your Coalesce environment
     
      - name: Deploy Plan
        run: npx coa deploy --config COA_CONFIG --plan ./coa-plan2 --debug
        
